import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/navbar";
import styles from "../styles/Home.module.css";
import Button from "@mui/material/Button";
import { createTheme, ThemeProvider } from "@mui/material/styles";

const theme = createTheme({
  palette: {
    primary: {
      // Purple and green play nicely together.
      main: "#FF5F00",
    },
    secondary: {
      // This is green.A700 as hex.
      main: "#11cb5f",
    },
  },
});

export default function Home() {
  return (
    <>
      <Navbar />
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <span style={{ color: "#FF5F00" }}>COMPANY</span>
          </h1>
          <ThemeProvider theme={theme}>
            <Button
              color="primary"
              variant="contained"
              style={{
                textTransform: "none",
                fontSize: "3vh",
                margin: "80px 0px",
                padding: "5px 35px",
              }}
              href="/investments"
            >
              Start investing now!
            </Button>
          </ThemeProvider>
        </main>
      </div>
    </>
  );
}
